version: "3.9"

services:
  app:
    build: .
    container_name: tummoc-app
    ports:
      - "5000:5000"
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: tumoc_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.0
    container_name: tummoc_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - prometheus
    restart: unless-stopped